Updated forward()
forward() was updated to work for multi_classification, solving File "C:\Python311\Lib\site-packages\torch\nn\modules\module.py", line 1519, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\torch\nn\modules\module.py", line 1528, in _call_impl
    return forward_call(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: BertFineTuneMini.forward() takes 3 positional arguments but 5 were given